workspace:
  base: /test
  path: openeuropa-site

services:
  web:
    image: fpfis/php71-dev
    environment:
      - DOCUMENT_ROOT=/test/openeuropa-site
  mysql:
    image: percona/percona-server:5.6
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  selenium:
    image: selenium/standalone-chrome:3.11
    environment:
      - DISPLAY=:99
      - SE_OPTS=-debug

pipeline:
  composer-install:
    group: prepare
    image: fpfis/php71-build
    volumes:
      - /cache:/cache
    commands:
      - composer install

  site-install:
    image: fpfis/php71-build
    commands:
      - ./vendor/bin/run drupal:site-install
      # Reset permission since installation runs as root. @todo Fix this.
      - chown -R 1000:1000 build/sites/default
      - chmod -R 777 /tmp

  grumphp:
    group: test
    image: fpfis/php71-build
    commands:
      - ./vendor/bin/grumphp run

  behat:
    group: test
    image: fpfis/php71-build
    commands:
      - ./vendor/bin/behat
